#
# 开源代码，仅供学习和交流研究使用，商用请联系三丙
# 微信：mohan_88888
# 抖音：程序员三丙
# 付费课程知识星球：https://t.zsxq.com/aKtXo
#


networks:
  sanbing-network:
    driver: bridge
    name: sanbing-network
    ipam:
      config:
        - subnet: 10.10.0.0/24

services:
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/sanbing/redis:7.4
    restart: always
    networks:
      - sanbing-network
    ports:
      - '6379:6379'
    environment:
      - 'REDIS_PASSWORD=sanbing'
